ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "paypalEmail" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "notifPushEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "notifEmailEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "rides" ADD COLUMN IF NOT EXISTS "tipAmount" DOUBLE PRECISION;
